### PR TITLE
Load validators from a validators list

### PR DESCRIPTION
**Pull request by pk910**
Hi @protolambda,

Thanks for this great tool :)

We're using it to build a new scheduled genesis state for a [test ephemeral testnet](https://github.com/pk910/test-testnet-repo).
Genesis validators are managed via a github repository which is open to public, so we cannot share mnemonics in there.

I've extended your tool to load a list of validators from a text file in addition to the mnemonic based generation.
The format of this file is a simple list of `<pubkey>:<credentials>:<balance>` entries, so no secrets are included there anymore and it can be managed in a public repository.

I've added a new flag `--validators` to specify a path to a validators list. It defaults to `validators.txt`.
If it's not found it doesn't matter as I've kept your current mnemonic based implementation and just concatenate the results.

I'm not really familiar with go, so I'm sorry if the implementation is a bit dirty at some points ;)

### CODE REVIEW

**Comment by protolambda** [comment]
Can you update the READMe.md with a sub-section that describes the usage/format of this feature in more detail?

**Comment by pk910** [comment]
I've added some documentation.

I've also changed the default value for the flag to an empty string.
That way there is no error printed out when using the default `--mnemonic` flag only.

**Comment by SpontaneousOverthrow** [comment]
Any updates here? This feature is very useful.

**Comment by protolambda** [comment]
Thanks for checking on the status. It generally looks good, but to avoid accidentally breaking any core L1 testnet tooling I'd like a sign-off from @parithosh before merging it.

**Comment by pk910** [comment]
Oh, there is some activity in here :D

The "feature" I've been adding is a fully optional thing and doesn't change any of the existing logic (just adds more validators from a text file).
However, it was actually my first go based code I've modified, so it's probably a bit dirty :D

I completely understand if you'd like to keep it in a separate branch, and I actually don't mind :)
As explained in the top comment I needed this feature to generate the ephemery genesis in a trust-less  & public way - without leaking any mnemonics.
I thought it'd be cool to merge it back to the upstream repository, but if not that's fine too.
If anyone needs the same modification, he can probably find it via this PR and build the tool himself.

Anyway, I'll keep this branch updated as the ephemery project depends on it.

**Comment by parithosh** [comment]
I just tested the PR and it is indeed a nice extra feature. I just had a few changes to request before merging:
- Rename the flag from `--validators` to `--additional-validators`, that way its a bit more clear that this file will not override the mnemonic related validators
- Rebase the PR on top of master as there have been large changes to the `capella.go` file

**Comment by pk910** [comment]
I've renamed the flag to `--additional-validators` and did some code cleanup to make the additional code shorter and more readable.
Also merged latest master, but it wasn't conflicting with the `capella.go` changes at all.

Tested the latest version with the updated flag for the ephemery genesis generation, which [works fine](https://github.com/ephemery-testnet/ephemery-genesis/actions/runs/5652024667/job/15311020385) :)

**Review by parithosh — APPROVED** [review]

**Comment by parithosh** [comment]
Great, merging this PR then :)

**Pull request merged**
